In [ ]:
# Homework review
# If we have a linked list where object 1 points to object 2 which points to object 3
# Each node has a value and a pointer to the next object
# This is a case where private methods might be useful

In [ ]:
# Regular expressions offer a way to handle strings and identify patterns.


In [4]:
import re

In [5]:
raw_string = 'Hi, how are you today?'
print re.search('Hi', raw_string)

In [6]:
s = re.search('Hi', raw_string)

In [8]:
print s.start() # the starting position of the matched string
print s.end() # the ending position of the matched string
print s.span() # a tuple containing the indices of the string

0
2
(0, 2)


In [14]:
# "." represents a single character

print re.search('a.', 'aa') != None
print re.search('a.', 'ab') != None
print re.search('a.', 'a1') != None
print re.search('a.', 'a#') != None
print re.search('a.', 'ba') != None
print re.search('a.', 'baa') != None
print re.search('a.b', 'ba') != None
print re.search('a.b', 'caba') != None

True
True
True
True
False
True
False
False


In [58]:
print re.search('ba?b', 'bb') != None # match
print re.search('ba?b', 'bab') != None
print re.search('ba?b', 'baab') != None
print re.search('ba?b', 'baabb') != None

True
True
False
True


In [56]:
print re.search('ba+b', 'bb') != None # match
print re.search('ba+b', 'bab') != None
print re.search('ba+b', 'baab') != None
print re.search('ba+b', 'baabc') != None

False
True
True
True


In [47]:
print re.search('ba*b', 'bb') != None
print re.search('ba*b', 'bab') != None
print re.search('ba*b', 'baaaaaaab') != None

True
True
True


In [22]:
print re.search('ba{1,3}b', 'bab') != None
print re.search('ba{1,3}b', 'baab') !=None
print re.search('ba{1,3}b', 'baaaaaaab') != None
print re.search('ba{1,3}b', 'bb') != None

True
True
False
False


In [25]:
# ^ refers to beginning of a text and $ refers to the ending of a text
# PAY ATTENTION TO WHITE SPACES!!
print re.search('^a', 'abc') != None
print re.search('^a','abcde') !=None
print re.search('^a', 'cabcde') != None

True
True
False


In [26]:
print re.search('a$', 'abc') != None
print re.search('a$', 'abcda') != None

False
True


In [27]:
# So ^a.a$ matches a text whose length is 3, begins with an a and ends with an a, such as aba
print re.search('^a.a$', 'aba') != None
print re.search('^a.a$', 'acba') != None
print re.search('^a.a$', 'cba') != None

True
False
False


In [30]:
print re.search('[123abc]', 'defg') != None
print re.search('[123abc]', '1defg') != None
print re.search('[123abc]', '2defg') != None
print re.search('[123abc]', 'adefg') != None
print re.search('[123abc]', 'bdefg') != None
print re.search('[1-3a-c]', 'defg') != None
# Brackets are basically saying or or or or or and the dash represents the range.

False
True
True
True
True
False


In [32]:
print re.search('(abc){2,3}', 'abc') != None
print re.search('(abc){2,3}', 'abcabc') != None
print re.search('(abc){2,3}', 'abcabcabc') != None
# () is similar to the mathematical meaning - it groups together the expressions contained inside them.

False
True
True


In [33]:
'abc'*4

'abcabcabcabc'

In [38]:
print re.search('(abc){2,3}', 4*'abc') != None
print re.search('(abc){2,3}8', 4*'abc') != None
print re.search('(abc){2,3}8', 3*'abc'+'8') != None

True
False
True


In [40]:
# Pipe operator (|) can replace ()
print re.search('abc|123', 'a') != None
print re.search('abc|123', '1') != None
print re.search('abc|123', 'abc') != None
print re.search('abc|123', 'xyz') != None
print re.search('abc|123', '123') != None

False
False
True
False
True


In [43]:
print re.search('\?', 'How are you today?') != None

True


In [ ]:
#re.sub function
# sub, split, findall
# 'n' is used for end of line

In [ ]:
# numpy
# This is the basis on which pandas is built
# Check out "coding the matrix" by philip n. klein


In [1]:
from numpy import array
a1 = array([1, 1, 1])
a2 = array([1, 2, 3])
a1 + a2

array([2, 3, 4])

In [3]:
#alternatively
import numpy as np
a1 = np.array([1,1,1])
a2 = array([1, 2, 3])
print a1 + a2

[2 3 4]


In [4]:
[1,2,3] + [4,5,6] # this concatinates the two lists but with arrays, it does element-wise addition

[1, 2, 3, 4, 5, 6]

In [18]:
a1 = [1, 2, 3]
a2 = [4, 5, 6]
a3 = []

for i in range(len(a1)):
    a3.append(a1[i] + a2[i])

print a3
help(a3.append)

[5, 7, 9]
Help on built-in function append:

append(...)
    L.append(object) -- append object to end



In [79]:
print a1
print a1*2
print a1*a2
print a2
print a2**2

[1 1 1]
[2 2 2]
[1 2 3]
[1 2 3]
[1 4 9]


In [82]:
a1 = array((1, 2, 3))
print a1[0]
print a1[1:]
print type(a1[1:])

1
[2 3]
<type 'numpy.ndarray'>


In [88]:
am = array([[1,2,3],[4,5,6]])
am

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
am[0][1]

2

In [90]:
am[0,1]

2

In [96]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
np.arange(9.5)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [106]:
np.arange(10, dtype = np.float)


array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [108]:
np.linspace(10,20)
# evenly spaced numbers in the specified range, default length is 50

array([ 10.        ,  10.20408163,  10.40816327,  10.6122449 ,
        10.81632653,  11.02040816,  11.2244898 ,  11.42857143,
        11.63265306,  11.83673469,  12.04081633,  12.24489796,
        12.44897959,  12.65306122,  12.85714286,  13.06122449,
        13.26530612,  13.46938776,  13.67346939,  13.87755102,
        14.08163265,  14.28571429,  14.48979592,  14.69387755,
        14.89795918,  15.10204082,  15.30612245,  15.51020408,
        15.71428571,  15.91836735,  16.12244898,  16.32653061,
        16.53061224,  16.73469388,  16.93877551,  17.14285714,
        17.34693878,  17.55102041,  17.75510204,  17.95918367,
        18.16326531,  18.36734694,  18.57142857,  18.7755102 ,
        18.97959184,  19.18367347,  19.3877551 ,  19.59183673,
        19.79591837,  20.        ])

In [109]:
np.linspace(10,20,5)

array([ 10. ,  12.5,  15. ,  17.5,  20. ])

In [110]:
np.zeros([3,2])

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [111]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [112]:
np.zeros([2,3])

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [116]:
from numpy import mat, matrix
# numpy lets you refer to matrices as either mat or matrix
# importing bth lets you refer to both, importing one only let's your refer to one
m1 = mat([1, 2, 3])
m1

matrix([[1, 2, 3]])

In [115]:
m2 = mat([[1,2,3],[4,5,6]])
m2

matrix([[1, 2, 3],
        [4, 5, 6]])

In [117]:
# Indexing matrices
m2[1]

matrix([[4, 5, 6]])

In [123]:
m2[1][0]

matrix([[4, 5, 6]])

In [121]:
m2[1,0]

4

In [124]:
m2[0]

matrix([[1, 2, 3]])

In [125]:
m1 = mat([[1,2,3],[4,5,6]])
m2 = mat([[1,2,3],[4,5,6]])
print m1 + m2
print m1 - m2
print m1 / m2
# addition, subtraction, multiplication work as expected.

[[ 2  4  6]
 [ 8 10 12]]
[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]


In [126]:
print m1*m2
# multiplication does not work as expected.

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [ ]:
# Transposing matrices...
# Switching the i and j components

In [128]:
print m1
print m1.T

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [130]:
m1*m2.T

matrix([[14, 32],
        [32, 77]])

In [134]:
m2 = array(m2)
print type(m2)

<type 'numpy.ndarray'>


In [149]:
# element wise multiplication
from numpy import multiply
#help(np.multiply)
multiply(m1, m2)

matrix([[ 1,  4,  9],
        [16, 25, 36]])

In [137]:
m1 = mat([[1,2],[3,4]])
print m1 ** 2

[[ 7 10]
 [15 22]]


In [139]:
from numpy import shape
m1 = mat([[1,2,3],[4,5,6]])
a1 = array([[1,2,3],[4,5,6]])
print shape(m1)
print shape(a1)

(2, 3)
(2, 3)


In [140]:
print a1.shape
print m1.shape

(2, 3)
(2, 3)


In [143]:
# RESHAPE
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [144]:
a1.reshape([6,1]) # make a1 a single column.

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [145]:
m1

matrix([[1, 2, 3],
        [4, 5, 6]])

In [146]:
m1.reshape([3,2])

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [152]:
print sum([1,2,3])
print average([1,2,3])

6


NameError: name 'average' is not defined

In [154]:
m = mat([3,2,1])
a = array(m)
print a

[[3 2 1]]


In [156]:
print m.sort()

None


In [157]:
# Random sampling
import numpy as np

In [158]:
from numpy import random

In [160]:
random.rand(2,3)

array([[ 0.63106963,  0.34717084,  0.34424186],
       [ 0.1805924 ,  0.23345781,  0.24297085]])

In [ ]:
# Standard normal distribution: mean = 0, standard deviation of 1.

In [161]:
random.randint(low = 1, high = 6, size = (5,5)) 

array([[3, 3, 4, 4, 4],
       [4, 3, 4, 4, 2],
       [1, 2, 5, 3, 1],
       [5, 5, 2, 5, 3],
       [2, 4, 2, 2, 2]])

In [162]:
random.rand(3,3)

array([[ 0.81624988,  0.41296024,  0.30039311],
       [ 0.23407605,  0.54402698,  0.42830289],
       [ 0.12093746,  0.06620182,  0.44929932]])

In [171]:
all_set = [1, 2, 3, 5, 8, 13, 21, 34, 55]
print random.choice(all_set, size = 10)
print random.choice(all_set, size = 5)
print random.choice(all_set, size = 3, replace = False)



[ 3  8 34 55  3  2 55 13 55  3]
[13  5  5 21 21]
[34 21  1]


Help on built-in function choice:

choice(...)
    choice(a, size=None, replace=True, p=None)
    
    Generates a random sample from a given 1-D array
    
            .. versionadded:: 1.7.0
    
    Parameters
    -----------
    a : 1-D array-like or int
        If an ndarray, a random sample is generated from its elements.
        If an int, the random sample is generated as if a was np.arange(n)
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    replace : boolean, optional
        Whether the sample is with or without replacement
    p : 1-D array-like, optional
        The probabilities associated with each entry in a.
        If not given the sample assumes a uniform distribution over all
        entries in a.
    
    Returns
    --------
    samples : 1-D ndarray, shape (size,)
        The generated ran