# Part 1: RegEx

(1) Write a function, **matchAll(pattern, listOstrings)**. Assume **pattern** argument will be a regular expression; assume the **listOstrings** argument will be a list of strings. Your function should return **True** if **pattern** matches all of the strings in the list.

In [4]:
import re

def matchAll(pattern, listOstrings):
    return all([re.search(pattern, string) != None for string in listOstrings])

#### Some Tests

In [2]:
print(matchAll('a', ['a', 'ab', 'abc'])) # True
print(matchAll('a', ['a', 'ab', 'bc']))  # False
print(matchAll('(ab)?', ['a', 'ab', 'abc']))  # True
print(matchAll('.', ['a', 'ab', 'abc']))      # True
print(matchAll('.{2,3}', ['a', 'ab', 'abc'])) # False

True
False
True
True
False


(2) Write a function, **matchNone(pattern, listOstrings)**, assuming the same type of arguments as the previous problem. Return True if the pattern does not match any one of the strings in the list.

In [12]:
import re

def matchNone(pattern, listOstrings):
    return all([re.search(pattern, string) == None for string in listOstrings])

#### Some Tests

In [17]:
print(matchNone('c', ['b', 'ba', 'bab']))      # True
print '-'*50
print(matchNone('a', ['b', 'bb', 'bbb']))      # True
print '-'*50
print(matchNone('a', ['b', 'ba', 'bab']))      # False
print '-'*50
print(matchNone('(ab)?', ['a', 'ab', 'ac']))   # False
print '-'*50
print(matchNone('a{2,}', ['a', 'aa', 'abc']))  # False
print '-'*50
print(matchNone('a{2,3}', ['a', 'ab', 'abc'])) # True

True
--------------------------------------------------
True
--------------------------------------------------
False
--------------------------------------------------
False
--------------------------------------------------
False
--------------------------------------------------
True


(3) Write a regular expression that matches the following words:

        a, an, absh, apple, adsorb, apple99

In [18]:
wordPattern = "a"
matchAll(wordPattern, ['a', 'an', 'absh', 'appale', 'adsorb', 'apple99']) # True

True

(4) Write a pattern that does not match the following words:
        
        can, fan, dan, ran, pan

In [20]:
wordPattern1 = '^(am)'## write your pattern here 
# Make this even simpler
wordPattern2 = "z"
print matchNone(wordPattern1, ['can', 'fan', 'dan', 'ran', 'pan']) # True
print matchNone(wordPattern2, ['can', 'fan', 'dan', 'ran', 'pan']) # True

True
True


(5) Write a regular expression that matches these three words: 

        - can, fan, dan
        
but **not** these three words: 

        - man, ran, pan

In [21]:
wordPattern = '^[cfd]+(an)$'
wordPattern2 = "[cfd]"
print matchAll(wordPattern, ['can', 'fan', 'dan']) # True
print matchAll(wordPattern2, ['can', 'fan', 'dan']) # True
print matchNone(wordPattern, ['man', 'ran', 'pan']) # True
print matchNone(wordPattern2, ['man', 'ran', 'pan']) # True

True
True
True
True


(6) Write a regular expression that matches these five words:

        - pit, spot, spate, slap two, respite
    
but **not** these four words:

        - pt, Pot, peat, part


In [23]:
wordPattern = 'p.t' # The word can start with any lower case letters. Then there can be any character between "p" and "t" and can end there or end with any additional characters.
#re.search(wordPattern, 'Pot')
wordPattern2 ="p([a-z]|\s)t" # Find a pattern that starts with a "p" and ends with a "t"
print matchAll(wordPattern, ['pit', 'spot', 'spate', 'slap two', 'respite']) # True
print matchNone(wordPattern, ['pt', 'Pot', 'peat', 'part']) # True
print matchAll(wordPattern2, ['pit', 'spot', 'spate', 'slap two', 'respite']) # True
print matchNone(wordPattern2, ['pt', 'Pot', 'peat', 'part']) # True

True
True
True
True


In [26]:
wordPattern = '(ap).?t'## write your pattern here
print matchAll(wordPattern, ['rap them', 'tapeth', 'apth', 'wrap/try', \
                             'sap tray', '87ap9th', 'apothecary']) # True
print matchNone(wordPattern, ['aleht', 'happy them', 'tarpth', 'Apt', 'peth', \
                              'tarreth', 'ddapdg', 'apples', 'shape the']) # True

True
True


# Part 2: NumPy

## Array Creation
Construct the following arrays without listing all of the elements. For example, you should use **np.ones(3)** to generate am array **array([1, 1, 1])** instead of **np.array([1, 1, 1])**.

(1) Construct an array of **float** ranging from 0-10.

In [30]:
## Write your code here.
import numpy as np
a1 = np.arange(11, dtype = float)
print a1

[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]


(2) Create an array containing 7 evenly spaced numbers between 0 and 23.

In [31]:
## Write your code here.
import numpy as np

a2 = np.linspace(0, 23, 7)
print a2

[  0.           3.83333333   7.66666667  11.5         15.33333333
  19.16666667  23.        ]


(3) Create a 3x3 matrix with values ranging from 0 to 8.

In [32]:
## Write your code here.
from numpy import mat, matrix
import numpy as np
a1 = np.array(range(9))
a2 = a1.reshape(3,3)
m2 = mat(a2)
print m2
print type(m2)
# Arrays vs. matrix
# Arrays are good for element wise operations
# When you get into working with data frames, they are built on top of these arrays. 

[[0 1 2]
 [3 4 5]
 [6 7 8]]
<class 'numpy.matrixlib.defmatrix.matrix'>


(4) Create a 5x5 matrix with row values ranging from 0 to 4.

$$\left[
\begin{array}{cc}
0 & 1 & 2 & 3 & 4 \\
0 & 1 & 2 & 3 & 4 \\
0 & 1 & 2 & 3 & 4 \\
0 & 1 & 2 & 3 & 4 \\
0 & 1 & 2 & 3 & 4 
\end{array}
\right]$$

In [33]:
## Write your code here.
import numpy as np

matSize = 5
m2 = np.zeros([matSize,matSize])

for i in range(matSize):
    m2[i] = range(matSize)

print m2

# another way to do this

a = np.arange(5)
m3 = np.mat([a, a, a, a, a])
print m3

# another way to do it
# Make use of the modulo operator
a2 = np.arange(25).reshape(5,5)%5
print a2

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


##Magic Matrices

(5) A magic square is a matrix whose row sums, column sums, and the sums of the two diagonals are equal. (One diagonal of a matrix goes from the top left to the bottom right, the other diagonal goes from top right to bottom left.)

Further more, a $n \times n$ magic matrix is constructed by $(1, 2, 3 ... n^2)$. For example, here is a $3\times 3$ magic array:
$$\left[
\begin{array}{cc}
8 & 1 & 6 \\
3 & 5 & 7 \\
4 & 9 & 2
\end{array}
\right]$$

Each number can only be used once.

Write a function to check whether a matrix is a magic matrix. You should check these three properties:

1. Is it a square matrix?
2. Is it constructed by $(1, 2, 3, ... n^2)$?
3. Are the sums of rows, columnsm, and diagnols the same? (Hint: the function **np.diag** may be useful)


## (Hint: the function **np.diag** may be useful)

In [170]:
def isMagic(theArray):
    # First, test to see if the matrix is 2-dimensional and square
    test1 = (len(theArray == 2) and (theArray.shape[0] == theArray.shape[1])) # This tests to see if the matrix is square
    # Second, test to see if the matrix is constructed by (1, 2, 3, ..., n^2) where n is the number of rows or columns.
    # Create a test array to compare to the array
    testArray = np.arange(theArray.shape[0]*theArray.shape[1]) + 1
    test2 = np.array_equal(testArray, np.sort(theArray.reshape(1, theArray.shape[0]*theArray.shape[1]))[0])
    # Lastly, test to see if the sum of all columns, rows and diagonals are the same
    # Create a baseline sum from the first row for comparisons
    baseline_sum = sum(theArray[0, :])
    # Check the row sums
    rowSum = np.all([sum(theArray[x, :]) for x in range(np.shape(theArray)[0])] == baseline_sum)
    # Check the column sums
    colSum = np.all([sum(theArray[:, x]) for x in range(np.shape(theArray)[0])] == baseline_sum)
    # Check the sum of the diagonals
    diagSum = sum(np.diag(theArray)) == baseline_sum
    # Check the backwards diagonal sum
    diagSum2 = sum(np.diag(np.fliplr(theArray))) == baseline_sum
    test3 = rowSum and colSum and diagSum and diagSum2
    return test1 and test2 and test3


In [171]:
theArray = np.array([[8, 1, 6], [3, 5, 7], [4, 9, 2]])
print theArray

isMagic(theArray)

[[8 1 6]
 [3 5 7]
 [4 9 2]]


True

### Some Tests

In [172]:
test1 = np.array([[0, 1], 
                  [1, 0]]) 
isMagic(test1) # False

False

In [173]:
test2 = np.array([[8, 1, 6],
                  [3, 5, 7],
                  [4, 9, 2]])
isMagic(test2) # True

True

In [174]:
test3 = np.array([[16, 2, 3, 13],
                  [5, 11, 10, 8],
                  [9,  7, 6, 12],
                  [4, 14, 15, 1]]) 
isMagic(test3) # True

True

In [175]:
test4 = np.array([[17, 24,  1,  8, 15],
                  [23,  5,  7, 14, 16],
                  [4,   6, 13, 20, 22],
                  [10, 12, 19, 21,  3],
                  [11, 18, 25, 2,   9]]) 
isMagic(test4) # True

True

In [176]:
test5 = np.array([[35, 1, 6, 26, 19, 24],
                  [3, 32, 7, 21, 23, 25],
                  [31, 9, 2, 22, 27, 20],
                  [8, 28, 33, 17, 10,15],
                  [30, 5, 34, 12, 14,16],
                  [4, 36, 29, 13, 18,11]])
isMagic(test5) # True

True